### PR TITLE
[fix] Dont rehash under fish shell

### PR DESCRIPTION
**Pull request by herder**
Not supported in fish

### CODE REVIEW

**Comment by bsucker98** [comment]
It didn't work for me tho, I just copied and pasted the changes and re-installed, but I should say im noob in these things 

This is what i get
`/tmp/.psub.E47f4svVCv (line 1): 
hash -r 2>/dev/null || true
^
from sourcing file /tmp/.psub.E47f4svVCv
	called on line 8 of file ~/.config/fish/functions/jenv.fish
in function 'jenv' with arguments 'rehash'
	called on line 6 of file /tmp/.psub.oovJRbzpnT
from sourcing file /tmp/.psub.oovJRbzpnT
	called on line 20 of file ~/.config/fish/config.fish
from sourcing file ~/.config/fish/config.fish
	called during startup
`

**Comment by hermitmaster** [comment]
`rehash` works fine for me under fish. What version are you using @herder?

**Comment by hermitmaster** [comment]
Duplicate of #169

**Comment by herder** [comment]
Hey, picking this up even though I don't use fish anymore - sorry for the late response!

You seem to have a `hash` binary in your path, but `hash` should refer to the builtin of zsh and bash:

```shell
❯ command -v hash
hash
```

```shell
❯ which -a hash
hash: shell built-in command
```

So I wonder if that's why you don't get the error we are getting, @hermitmaster

**Comment by herder** [comment]
Doing some cleanup in my old PR:s - this one seems to have no actitity, so I'm closing.

**Pull request closed without merging**
