### PR TITLE
Improve formatting and indentation.

### PR DESCRIPTION
**Pull request by johnjohndoe**

### CODE REVIEW

**Comment by johnjohndoe** [comment]
🔔

**Comment by LIttleAncientForestKami** [comment]
I took the liberty of solving the conflicts and have included it in #186.

**Comment by voronaam** [comment]
Another PR whose changes were already applied in another [PR](https://github.com/jenv/jenv/pull/186).

This one can be closed.

**Comment by johnjohndoe** [comment]
Okay. Thanks.

**Pull request closed without merging**
