### PR TITLE
Use the precmd hook instead of the chpwd hook

### PR DESCRIPTION
**Pull request by emcrisostomo**
Solves #258

### CODE REVIEW

**Comment by gcuisinier** [comment]
Hi ! 
Thank you for your proposal.

Can you explain me the advantage to use precmp ?

**Comment by emcrisostomo** [comment]
#258 i caused by the current implementation using the `chpwd` hook: as its name implies, it's triggered by a directory change. And why would I want to (have to) change the current directory for the change to be applied? Actually, I found the bug because I was reconfiguring my Java environment _in the same project_.

The `precmd` hook is triggered before each prompt, and that fits well this use case.

**Comment by gcuisinier** [comment]
Thank you for the info ! 👍 
And thank you for the contribution ! 🙏

**Comment by emcrisostomo** [comment]
Thanks @gcuisinier

**Pull request merged**
