### PR TITLE
Add .gitignore file

### PR DESCRIPTION
**Pull request by spodkowinski**
Do you mind adding a .gitignore file?

### CODE REVIEW

**Comment by x4121** [comment]
Maybe absolute file names would be better, to not match anything unintended:
```/shims
/version
/versions
/*.time
```
Otherwise, I hope this is getting merged soon :+1:

**Comment by lvorona** [comment]
There is already a good `.gitignore` file and this PR can be safely closed.

**Comment by gcuisinier** [comment]
Thank for the feedback @lvorona

**Comment by voronaam** [comment]
No problem. I was working with locally modified scripts for a while and just decided to put them up for everybody to use, if they want those changes.

I have set it up as a proper fork, linking to your project and pages everywhere and highlighting the differences: https://github.com/voronaam/jenv-fork

Then I decided to go over the PRs here to see what I find useful and merge them as well.

This is just an FYI. I intend to test the changes on various OSes and shell combinations and document all the results  in the fork's README. I will then go over the PRs I tested and leave a comment with the test results, if those were all good.

**Pull request closed without merging**
