### PR TITLE
[Fix][Doc] Fix typo and add location path

### PR DESCRIPTION
**Pull request by Fabszn**
I tried to use Jenv with Fish Shell. 
I faced with path error due to missing 's' on function word of fish config directory

### CODE REVIEW

**Comment by hermitmaster** [comment]
This is an important, yet trivial PR. Please merge it.

**Comment by hermitmaster** [comment]
Duplicate of #282

**Comment by voronaam** [comment]
Another byte-identical PR for the fish path instructions. PR #307, PR #282 and PR #291 are all exactly the same change. One of them should be merged, the rest closed.

**Comment by gcuisinier** [comment]
#307 merged

**Pull request closed without merging**
